[build]
  functions = "func"
  command = "npx webpack && go get ./func/... && go build -o func/parse-media-type ./func/..."

[build.environment]
  GO_IMPORT_PATH="github.com/kaganjd/redirect-express-functions" 

[context.deploy-preview.environment]
  DEPLOY_PREVIEW_KEY = "this is only available in context.deploy-preview"

[[headers]]
  for = "/.netlify/functions/encoding-bug"
  [headers.values]
    content-type = "image/png"
  
[[redirects]]
  from = "/skip-ci"
  to = "/.netlify/functions/skip-ci"
  status = 200

[[redirects]]
  from = "/withoutexpress"
  to = "/.netlify/functions/withoutexpress"
  status = 200

[[redirects]]
  from = "/withexpress"
  to = "/.netlify/functions/withexpress"
  status = 200
  signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/proxy"
  to = "https://competent-curran-1788d6.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false