[build]
  functions = "functions"
  ignore = "git diff --quiet HEAD^ HEAD new-dir/"

[[redirects]]
  from = "/withoutexpress"
  to = "/.netlify/functions/withoutexpress"
  status = 200

[[redirects]]
  from = "/withexpress"
  to = "/.netlify/functions/withexpress"
  status = 200
  signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false