[build]
  functions = "func"
  command = "npx webpack && cd func/firebase/ && npm install && cd ../../ && cd func/send-down-pdf/ && npm install"

[build.environment]
  GO_IMPORT_PATH="github.com/kaganjd/examples" 
  PLUGIN_VAR_TEST="this is the value of PLUGIN_VAR_TEST"

[dev]
  functions = "dev-func"

[context.deploy-preview.environment]
  DEPLOY_PREVIEW_KEY = "this is only available in context.deploy-preview"

[[plugins]]
package = "/plugins/what-happened"

[[plugins]]
package = "@netlify/plugin-local-install-core"

[[redirects]]
  from = "/return-path/*"
  to = "/.netlify/functions/return-path/:splat"
  status = 200

[[redirects]]
  from = "/return-host"
  to = "/.netlify/functions/return-host"
  status = 200

[[redirects]]
  from = "/skip-ci"
  to = "/.netlify/functions/skip-ci"
  status = 200

[[redirects]]
  from = "/withoutexpress"
  to = "/.netlify/functions/withoutexpress"
  status = 200
  force = true

[[redirects]]
  from = "/withexpress"
  to = "/.netlify/functions/withexpress"
  status = 200

[[redirects]]
  from = "/proxy"
  to = "https://competent-curran-1788d6.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/next-slugs/_next/*"
  to = "/next-slugs/_next/:splat"
  status = 200
  force = false 

[[redirects]]
  from = "/next-slugs/_next/*"
  to = "/.netlify/functions/return-path/:splat"
  status = 200
  force = false 

[[redirects]]
  from = "/Redirect"
  to = "https://google.com"
  status = 301
  force = true
