[build]
  functions = "functions"

[context.deploy-preview.environment]
  SKIP_KEY = "test value"
  
[[redirects]]
  from = "/skip-ci"
  to = "/.netlify/functions/skip-ci"
  status = 200

[[redirects]]
  from = "/withoutexpress"
  to = "/.netlify/functions/withoutexpress"
  status = 200

[[redirects]]
  from = "/withexpress"
  to = "/.netlify/functions/withexpress"
  status = 200
  signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/proxy"
  to = "https://competent-curran-1788d6.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false