[build]
  functions = "func"
  command = "npx webpack && cd func/send-down-pdf/ && npm install && cd ../../ && go get ./func/... && go build -o func/parse-media-type ./func/..."

[build.environment]
  GO_IMPORT_PATH="github.com/kaganjd/examples" 

[context.deploy-preview.environment]
  DEPLOY_PREVIEW_KEY = "this is only available in context.deploy-preview"

[[redirects]]
  from = "/my-name/*"
  to = "/my-name"
  status = 200
  force = true

[[redirects]]
  from = "/return-path/*"
  to = "/.netlify/functions/return-path/:splat"
  status = 200

[[redirects]]
  from = "/return-host"
  to = "/.netlify/functions/return-host"
  status = 200

[[redirects]]
  from = "/query-params"
  to = "https://pronoun.is/"
  status = 301
  query = {id = ":id"}

[[redirects]]
  from = "/forced-redirect"
  to = "https://pronoun.is/"
  status = 301
  force = true
  query = {id = ":id"}

[[redirects]]
  from = "/forced-redirect-retain-param"
  to = "https://pronoun.is/:p"
  status = 301
  force = true
  query = {pronoun = ":p"}

[[redirects]]
  from = "/skip-ci"
  to = "/.netlify/functions/skip-ci"
  status = 200

[[redirects]]
  from = "/withoutexpress"
  to = "/.netlify/functions/withoutexpress"
  status = 200

[[redirects]]
  from = "/withexpress"
  to = "/.netlify/functions/withexpress"
  status = 200
  signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/proxy"
  to = "https://competent-curran-1788d6.netlify.app/"
  status = 200
  force = true